/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'difficulty' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'questionText' : IDL.Text,
  'category' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Signature = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const SurveyResponse = IDL.Record({
  'barriers' : IDL.Vec(IDL.Text),
  'values' : IDL.Vec(IDL.Text),
  'ratings' : IDL.Vec(IDL.Nat),
  'reflection' : IDL.Text,
  'statistics' : IDL.Vec(IDL.Bool),
});

export const idlService = IDL.Service({
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByCategoryAndDifficulty' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByDifficulty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getRemainingSignatures' : IDL.Func([], [IDL.Nat], ['query']),
  'getSignatureCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSignatures' : IDL.Func([], [IDL.Vec(Signature)], ['query']),
  'getSurveyResponse' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SurveyResponse)],
      ['query'],
    ),
  'signPetition' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'submitSurvey' : IDL.Func([IDL.Text, SurveyResponse], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'difficulty' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'questionText' : IDL.Text,
    'category' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Signature = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const SurveyResponse = IDL.Record({
    'barriers' : IDL.Vec(IDL.Text),
    'values' : IDL.Vec(IDL.Text),
    'ratings' : IDL.Vec(IDL.Nat),
    'reflection' : IDL.Text,
    'statistics' : IDL.Vec(IDL.Bool),
  });
  
  return IDL.Service({
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByCategoryAndDifficulty' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByDifficulty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getRemainingSignatures' : IDL.Func([], [IDL.Nat], ['query']),
    'getSignatureCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSignatures' : IDL.Func([], [IDL.Vec(Signature)], ['query']),
    'getSurveyResponse' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SurveyResponse)],
        ['query'],
      ),
    'signPetition' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'submitSurvey' : IDL.Func([IDL.Text, SurveyResponse], [], []),
  });
};

export const init = ({ IDL }) => { return []; };