/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Question {
  'difficulty' : string,
  'correctAnswer' : bigint,
  'questionText' : string,
  'category' : string,
  'options' : Array<string>,
}
export interface Signature {
  'name' : string,
  'message' : [] | [string],
  'timestamp' : bigint,
}
export interface SurveyResponse {
  'barriers' : Array<string>,
  'values' : Array<string>,
  'ratings' : Array<bigint>,
  'reflection' : string,
  'statistics' : Array<boolean>,
}
export interface _SERVICE {
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getQuestionsByCategory' : ActorMethod<[string], Array<Question>>,
  'getQuestionsByCategoryAndDifficulty' : ActorMethod<
    [string, string],
    Array<Question>
  >,
  'getQuestionsByDifficulty' : ActorMethod<[string], Array<Question>>,
  'getRemainingSignatures' : ActorMethod<[], bigint>,
  'getSignatureCount' : ActorMethod<[], bigint>,
  'getSignatures' : ActorMethod<[], Array<Signature>>,
  'getSurveyResponse' : ActorMethod<[string], [] | [SurveyResponse]>,
  'signPetition' : ActorMethod<[string, [] | [string]], undefined>,
  'submitSurvey' : ActorMethod<[string, SurveyResponse], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];